# Autogenerated wrapper script for SimpleITK_jll for x86_64-linux-gnu
export libSimpleITKBasicFilters0, libSimpleITKBasicFilters1, libSimpleITKCommon, libSimpleITKIO, libSimpleITKRegistration, libSimpleITK_ITKCommon, libSimpleITK_ITKImageCompose, libSimpleITK_ITKImageFeature, libSimpleITK_ITKImageIntensity, libSimpleITK_ITKImageSources, libSimpleITK_ITKRegistrationCommon, libSimpleITK_ITKSuperPixel, libSimpleITK_ITKThresholding, libSimpleITK_SimpleITKFilters

JLLWrappers.@generate_wrapper_header("SimpleITK")
JLLWrappers.@declare_library_product(libSimpleITKBasicFilters0, "libSimpleITKBasicFilters0-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITKBasicFilters1, "libSimpleITKBasicFilters1-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITKCommon, "libSimpleITKCommon-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITKIO, "libSimpleITKIO-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITKRegistration, "libSimpleITKRegistration-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKCommon, "libSimpleITK_ITKCommon-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKImageCompose, "libSimpleITK_ITKImageCompose-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKImageFeature, "libSimpleITK_ITKImageFeature-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKImageIntensity, "libSimpleITK_ITKImageIntensity-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKImageSources, "libSimpleITK_ITKImageSources-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKRegistrationCommon, "libSimpleITK_ITKRegistrationCommon-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKSuperPixel, "libSimpleITK_ITKSuperPixel-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_ITKThresholding, "libSimpleITK_ITKThresholding-2.2.so.1")
JLLWrappers.@declare_library_product(libSimpleITK_SimpleITKFilters, "libSimpleITK_SimpleITKFilters-2.2.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libSimpleITKBasicFilters0,
        "lib/libSimpleITKBasicFilters0-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITKBasicFilters1,
        "lib/libSimpleITKBasicFilters1-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITKCommon,
        "lib/libSimpleITKCommon-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITKIO,
        "lib/libSimpleITKIO-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITKRegistration,
        "lib/libSimpleITKRegistration-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKCommon,
        "lib/libSimpleITK_ITKCommon-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKImageCompose,
        "lib/libSimpleITK_ITKImageCompose-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKImageFeature,
        "lib/libSimpleITK_ITKImageFeature-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKImageIntensity,
        "lib/libSimpleITK_ITKImageIntensity-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKImageSources,
        "lib/libSimpleITK_ITKImageSources-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKRegistrationCommon,
        "lib/libSimpleITK_ITKRegistrationCommon-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKSuperPixel,
        "lib/libSimpleITK_ITKSuperPixel-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_ITKThresholding,
        "lib/libSimpleITK_ITKThresholding-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSimpleITK_SimpleITKFilters,
        "lib/libSimpleITK_SimpleITKFilters-2.2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
